### ISSUE TITLE
Transfer improvements from 57-perception-shield-study

### ISSUE THREAD

**Issue by biancadanforth** [gregglind/template-shield-study#10]
Gregg made a lot of improvements to [57-perception-shield-study](https://github.com/gregglind/57-perception-shield-study).

Let's identify those improvements and make sure we pull them into the template study, SSAU, etc.

Here are a few I am aware of:
* Add [TELEMETRY.md](https://github.com/gregglind/57-perception-shield-study/blob/functional-tests/TELEMETRY.md) and [TESTPLAN.md](https://github.com/gregglind/57-perception-shield-study/blob/functional-tests/TESTPLAN.md)
* Incorporate automated (`functional_tests.js`) improvements that compare expected to actual state for first (left-most) button press. TODO add automated tests for *all* button presses.
* Consider making/amending a helper addon for [telemetry ping data console.logs](https://github.com/gregglind/57-perception-shield-study/blob/functional-tests/TESTPLAN.md#telemetry-ping-printing-helper-code) for QA.

@gregglind , can you list out any other improvements here so we can make sure we bring those in as well?

**Comment by motin** [comment]
> Consider making/amending a helper addon for telemetry ping data console.logs for QA.

I added this as part of the `npm run firefox` output in https://github.com/gregglind/template-shield-study/pull/15

**Comment by gregglind** [comment]
Thanks.  Will look that over.
