### ISSUE TITLE
Make it possible to watch changes and have the extension reload automatically

### ISSUE THREAD

**Issue by motin** [gregglind/template-shield-study#16]
Preferably with the option of clearing storage automatically as well.

**Comment by gregglind** [comment]
This only kind of works.  "reload" for Legacy xpi's is... dicey.  

I claim this is a CANTFIX, except for these condidtions:

- the webExtension part already does this with `web-ext run`
- the LEGACY part can't force reload in the way that guarantees Cu.unload works correctly ALWAYS.

The alternative path is `run-firefox.js`
