### ISSUE TITLE
should this project be stand alone?  Or part of SSAI

### ISSUE THREAD

**Issue by gregglind** [gregglind/template-shield-study#2]

**Comment by motin** [comment]
@gregglind Noob question here, but what is SSAI? Shield studies automated infrastructure?

**Comment by motin** [comment]
As a newcomer, I'd expect that this template would be found at https://github.com/mozilla/shield-studies-addon-template

Related: https://github.com/mozilla/shield-studies-addon-template/issues/16

**Comment by gregglind** [comment]
MOVED!
