### ISSUE TITLE
imrpove logging patterns

### ISSUE THREAD

**Issue by gregglind** [gregglind/template-shield-study#7]

**Comment by gregglind** [comment]
- https://github.com/mozilla/normandy/blob/master/recipe-client-addon/lib/LogManager.jsm
- https://github.com/mozilla/normandy/blob/master/recipe-client-addon/lib/ShieldRecipeClient.jsm#L53

**Comment by motin** [comment]
+1

Btw, since GeckoDriver does not implement the selenium log endpoint, we can't access the browser logs from the tests.
